data:
  scans_path: '/cluster/project/cvg/weders/data/scannet/scans/'
  masks:
    masks_path: '/cluster/scratch/efedele/masks' #scannet200
    masks_suffix: '*_masks.pt'
  camera:
    poses_path: 'pose/'
    intrinsic_path: 'intrinsic/intrinsics.txt'
    # intrinsic_resolution: [968, 1296] 
    intrinsic_resolution: [240, 320] 
  depths:
    depths_path: 'depth/'
    depths_ext: '.png'
    depth_scale: 1000
  images:
    images_path: 'color/'  
    images_ext: '.jpg'

openmask3d:
  top_k: 5
  multi_level_expansion_ratio: 0.1
  num_of_levels: 3
  vis_threshold: 0.2
  frequency: 1
  num_random_rounds: 10
  num_selected_points: 5

external:
  feature_extractor_type: 'siglip'  # Options: 'clip', 'siglip'
  sam_checkpoint: '/cluster/scratch/efedele/checkpoints/sam_vit_h_4b8939.pth'
  sam_model_type: 'vit_h'
  clip_model: 'ViT-L/14@336px'
  # siglip_model: 'google/siglip-base-patch16-224'
  # siglip_model: 'google/siglip-so400m-patch14-384'
  siglip_model: 'google/siglip-base-patch16-384'

output:
  experiment_name: 'experiment'
  output_directory: '/cluster/scratch/efedele/'
  save_crops: False

gpu:
  optimize_gpu_usage: False